### ISSUE TITLE
Shield items [Wires, Tie, QSS] don't increase shields with Transcendence

### ISSUE THREAD

**Issue by sanity-dance** [Keroro1454/Supply-Drop#6] opened 2020-12-26 07:34 UTC
The Personal Shield Generator in the base game increases your shields by 8% of your max health before taking Transcendence; I believe the shield items in this mod are attempting to increase your shields by a percentage of your max health after taking Transcendence, which is 1.

**Comment by Keroro1454** [comment] 2021-01-10 08:56
Going to look into this for a patch in 1.4, is likely caused by the switch to the TILER2 hook over my own IL hook. If so, will switch back until TILER fixes things.

**Comment by Keroro1454** [comment] 2021-01-12 03:51
Just ran a test with Transcendence where Unassuming Tie utilized TILER2's hook, and Salvaged Wires utilized my own. Both appeared to give the proper amount of shield. If you can document the error you believe to be experiencing, please feel free to open a new issue, but as for now I'm going to close this as solved.

**Closed as completed by Keroro1454** 2021-01-12 03:51 UTC

**Comment by sanity-dance** [comment] 2021-01-12 20:30
Here is the documentation you requested.

All mods other than Supply Drop and its dependencies have been disabled.

In a previous test, I noted some inconsistencies. After picking up a QSS, subsequent stacks of Wires and Ties increased shields properly. I have not been able to reproduce this behavior.

![shieldbefore](https://user-images.githubusercontent.com/58183513/104369045-c1b9a800-54d1-11eb-8517-f3fe57689d78.png)

![shieldafter](https://user-images.githubusercontent.com/58183513/104369065-c54d2f00-54d1-11eb-84b1-7c90e03c32fe.png)

![shieldafter2](https://user-images.githubusercontent.com/58183513/104369079-c7af8900-54d1-11eb-9c44-412b532b74e8.png)

![shieldafter3](https://user-images.githubusercontent.com/58183513/104369093-caaa7980-54d1-11eb-87db-989beda4224f.png)

![shieldafter4](https://user-images.githubusercontent.com/58183513/104369099-cc743d00-54d1-11eb-88c4-a337a0be3e73.png)
