### ISSUE TITLE
Healing being reduced due to attack speed or certain proc items

### ISSUE THREAD

**Issue by SyfleNov** [Keroro1454/Supply-Drop#11] opened 2021-01-17 09:04 UTC
Hello Keroro1454 I noticed a bug during one of my runs where I was getting less and less healing from items. It came to the point where any healing I received was being reduced to just 1. It didn't matter if it was bustling fungus, harvester scythe, medkit, or the leaching seed. I found it weird because the moment I noticed it being reduced to 1 was the moment my run died.

So through some trial and error going through disabling many mods I found that it was yours causing this weird bug. So I created a new profile in RoR2mod man with your mod, bepinexpack, r2api, tiler2, rorcheats by loadington, and risk of options by rune850. I was able to recreate the bug with ease. The moment I disable your mod, the healing goes back to normal. I am not sure what part of your mod is causing it.

How to get this bug in RoR2 with Supply drop:
-Acquire healing items
-Acquire a Soldiers Syringe/Molten Perforator/Tri-tipped Knife/Bundle of Rockets/Sticky Bomb/ Gasoline/ Sentient Meat hook/ AtG Missile Mk. 1 in vast quantaties usually more noticeable past 10 of one item.
-Notice drop in healing as you acquire more of the items above

Mods Used:
-BeppinExPack by beppis
-R2API by tristanmcpherson
-TILER2 by ThinkInvis
-Supply Drop by Keroro1454
-Risk of Options by Rune850 (Is a mod RoR2Cheats is dependent on)
-RoR2Cheats by Loadington (Used this to get the items to recreate the bug)

Recorded this bug on video:
https://www.youtube.com/watch?v=7oA2TwCVIzg

Can provide more recordings if needed.

**Comment by Keroro1454** [comment] 2021-01-18 08:45
I believe this has been fixed as of 1.4.3, please let me know if you find any other issues (or if the issue is somehow still popping up). Thank you for the report!

**Closed as completed by Keroro1454** 2021-01-18 08:45 UTC
